[build]
  command = "CI=false npm run build"
  publish = "dist"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-functions", "firebase-admin", "cors"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https://*.googleapis.com https://*.gstatic.com https://*.google.com https://*.firebaseio.com https://*.cloudfunctions.net;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://*.gstatic.com https://*.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: blob: https://*.googleapis.com https://*.gstatic.com https://*.google.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://*.cloudfunctions.net;
      frame-src 'self' https://*.firebaseapp.com;
      object-src 'none';
    """
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
